"""Regression contracts for the canonical locked Python packaging surface."""

from __future__ import annotations

import subprocess
import tomllib
from pathlib import Path
from typing import cast


ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = ROOT / "pyproject.toml"
REQUIREMENTS = ROOT / "requirements.txt"


def _configuration() -> dict[str, object]:
    with PYPROJECT.open("rb") as source:
        return tomllib.load(source)


def _project() -> dict[str, object]:
    return cast(dict[str, object], _configuration()["project"])


def _non_comment_lines(value: str) -> list[str]:
    return [line for line in value.splitlines() if line and not line.startswith("#")]


def test_project_metadata_declares_supported_runtime_and_locked_groups() -> None:
    project = _project()
    dependencies = cast(list[str], project["dependencies"])
    groups = cast(dict[str, list[str]], _configuration()["dependency-groups"])

    assert project["requires-python"] == ">=3.14,<3.15"
    assert "streamlink==8.4.0" in dependencies

    assert {"dev", "test", "typing", "security"} <= set(groups)
    assert "ruff==0.15.1" in groups["dev"]
    production = set(dependencies)
    tooling = {dependency for group in groups.values() for dependency in group}
    assert not production & tooling


def test_requirements_export_is_locked_uv_production_export() -> None:
    completed = subprocess.run(
        [
            "uv",
            "export",
            "--locked",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert REQUIREMENTS.read_text(encoding="utf-8").startswith(
        "# This file was autogenerated by uv via the following command:\n"
    )
    assert _non_comment_lines(
        REQUIREMENTS.read_text(encoding="utf-8")
    ) == _non_comment_lines(completed.stdout)


def test_lock_and_runtime_consumers_are_canonical() -> None:
    assert (ROOT / "uv.lock").is_file()

    dockerfile = (ROOT / "docker" / "Dockerfile").read_text(encoding="utf-8")
    workflow = (ROOT / ".github" / "workflows" / "test.yml").read_text(encoding="utf-8")
    assert "uv export --locked --no-dev" in dockerfile
    assert "uv lock --check" in workflow
    assert "uv sync --locked --all-groups" in workflow


def test_wheel_build_uses_metadata_without_importing_application(
    tmp_path: Path,
) -> None:
    subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(tmp_path)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    assert list(tmp_path.glob("streamvault-*.whl"))


def test_locked_environment_exposes_ruff_without_host_fallback() -> None:
    completed = subprocess.run(
        ["uv", "run", "--locked", "ruff", "--version"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    assert completed.stdout.startswith("ruff 0.15.1")


def test_no_environment_secret_file_is_tracked() -> None:
    tracked = subprocess.run(
        ["git", "ls-files", "--error-unmatch", ".env"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert tracked.returncode != 0
