version: '3.8'

services:
  app:
    build: .
    container_name: streamvault_local
    volumes:
      # Mount source code for hot reloading
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./.env:/app/.env
      # Local data directories
      - ./recordings_local:/recordings
      - ./data_local:/app/data
      - ./logs_local:/app/logs
    ports:
      - "7000:7000"
    environment:
      - PUID=1000
      - PGID=1000
      - TWITCH_APP_ID=${TWITCH_APP_ID}
      - TWITCH_APP_SECRET=${TWITCH_APP_SECRET}
      - BASE_URL=${BASE_URL}
      - EVENTSUB_SECRET=${EVENTSUB_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: streamvault_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_local:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port for local access
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data_local:
