services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamvault
    container_name: streamvault
    restart: unless-stopped
    ports:
      - "9000:9000"
    tty: true
    environment:
      - APP_URL=https://twitch.mebert-server.de
      - DB_CONNECTION=mysql
      - DB_HOST=streamvault_db
      - DB_PORT=3306
      - DB_DATABASE=mytwitchproject
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - TZ=Europe/Berlin
      - TWITCH_CLIENT_ID=fx4xg7kx7fwksmm7qxgi3cux496lp3
      - TWITCH_CLIENT_SECRET=ml9ilsxy7xmcjtdbb6r2slddd1xxy4
      - LOG_CHANNEL=stderr
      - REVERB_SCALING_ENABLED=true
    volumes:
      - ./:/var/www
      - ./recordings:/var/www/storage/app/recordings
    networks:
      - streamvault-network
    depends_on:
      - streamvault_db
      - streamvault_redis

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - streamvault-network
    depends_on:
      - app

  streamvault_redis:
    image: redis:alpine
    container_name: streamvault_redis
    networks:
      - streamvault-network

  streamvault_db:
    image: mariadb:10.5
    container_name: streamvault_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mytwitchproject
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - streamvault-dbdata:/var/lib/mysql
    networks:
      - streamvault-network

volumes:
  streamvault-dbdata:

networks:
  streamvault-network:
    driver: bridge