services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - recordings:/recordings
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - BASE_URL=https://streamvault.mebert-server.de
      # - FLASK_APP=app.py
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - RECORDINGS_DIR=/recordings/
      - TWITCH_CLIENT_ID=fx4xg7kx7fwksmm7qxgi3cux496lp3
      - TWITCH_CLIENT_SECRET=6cjpoghuodvlm1jaj5m9hy2y9d626b
      - TWITCH_WEBHOOK_SECRET=ogDEi3@#CQ5L3xFu7qGNq#!9UPdzwrGD
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EVENTSUB_WEBHOOK_PORT=8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
      - ./instance:/usr/src/app/instance
      - recordings:/recordings
    environment:
      - BASE_URL=https://streamvault.mebert-server.de
      - RECORDINGS_DIR=/recordings/
      - TWITCH_CLIENT_ID=fx4xg7kx7fwksmm7qxgi3cux496lp3
      - TWITCH_CLIENT_SECRET=6cjpoghuodvlm1jaj5m9hy2y9d626b
      - TWITCH_WEBHOOK_SECRET=ogDEi3@#CQ5L3xFu7qGNq#!9UPdzwrGD
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      web:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels "[{connection,error}]"
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  rabbitmq_data:
  recordings:
