services:
  app:
    build: .
    image: streamvault
    container_name: streamvault
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    environment:
      - APP_URL=https://twitch.mebert-server.de
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mytwitchproject
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - TZ=Europe/Berlin
      - TWITCH_CLIENT_ID=fx4xg7kx7fwksmm7qxgi3cux496lp3
      - TWITCH_CLIENT_SECRET=ml9ilsxy7xmcjtdbb6r2slddd1xxy4
      - LOG_CHANNEL=stderr
      - TRUSTED_PROXIES=192.168.178.77
    volumes:
      - ./:/var/www
      - ./recordings:/var/www/storage/app/recordings
    networks:
      - app-network
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: streamvault_redis
    networks:
      - app-network


  db:
    image: mariadb:10.5
    container_name: streamvault_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mytwitchproject
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
      - .docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
