// Generated by scripts/generate-responsive-tokens.mjs. Do not edit.

export const layoutQueries = {
  player: '(max-width: 767px)',
  shell: '(max-width: 1023.98px)',
} as const

export type LayoutQueryName = keyof typeof layoutQueries
