"""Add hashed refresh-token family storage for JWT rotation."""

from sqlalchemy import inspect, text


def upgrade(engine):
    with engine.begin() as connection:
        postgres = connection.dialect.name == "postgresql"
        identifier = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if postgres
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        timestamp = "TIMESTAMP WITH TIME ZONE" if postgres else "DATETIME"
        user_columns = {
            column["name"] for column in inspect(connection).get_columns("users")
        }
        if "is_active" not in user_columns:
            connection.execute(
                text(
                    "ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE"
                )
            )
        connection.execute(
            text(f"""
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                id {identifier}, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                family_id VARCHAR(64) NOT NULL, token_hash VARCHAR(64) NOT NULL UNIQUE,
                expires_at {timestamp} NOT NULL, family_expires_at {timestamp} NOT NULL,
                used_at {timestamp}, revoked_at {timestamp}, parent_token_hash VARCHAR(64),
                created_at {timestamp} DEFAULT CURRENT_TIMESTAMP
            )
        """)
        )
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS ix_refresh_tokens_family_id ON refresh_tokens (family_id)"
            )
        )
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens (user_id)"
            )
        )


def downgrade(engine):
    with engine.begin() as connection:
        connection.execute(text("DROP TABLE IF EXISTS refresh_tokens"))
