name: Python Code Quality

on:
  push:
    paths:
      - 'app/**'
      - 'migrations/**'
      - 'requirements.txt'
      - '.github/**/*.yml'
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Check syntax errors
        run: |
          python -m flake8 app migrations --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Check undefined variables and imports
        run: |
          python -m flake8 app migrations --count --select=F821,F822,E999,F401 --show-source --statistics

  import-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run import test
        run: |
          python import_test.py
