name: Release Drafter

on:
  push:
    branches:
      - main  # Nur auf main, nicht develop
  pull_request_target:  # Verwendet pull_request_target statt pull_request
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Checkout repository to access config file
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
